matrix:
  include: 
    - env: FOO=123
      script: python -c "import os; print os.environ['FOO']" 
    - env: FOO=456
      script: python -c "import os; print os.environ['FOO']"
    - env: FOO=789
  
  
script: python -c "import os; print os.environ['FOO']"
